include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true # Uncomment to enable the `prefer_single_quotes` rule
    require_trailing_commas: true # Uncomment to enable the `require_trailing_commas` rule

analyzer:
  errors:
    invalid_annotation_target: ignore

  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
